[package]
name = "divsufsort"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[features]
crosscheck = ["once_cell"]

[dependencies]
once_cell = { version = "1.2.0", optional = true }
sacabase = { path = "../sacabase" }
